### ISSUE TITLE
Emap macro expansion not working

### ISSUE THREAD

**Issue by grcasanova** [emergent-design/libentity#2]
In the following snippet the _emap_ macro doesn't seem to work, compilation always failing with

> Static_assert failed "Item must contain a description, have you missed a public 'emap()' definition in your entity?"

```
class Message
        {
        public:
            Message(std::string payload,) : m_payload(payload) {}

            bool isValid()
            {
                if(m_payload.size() > 0)
                    return true;
                else
                    return false;
            }
       
            std::string getPayload()
            {
                return m_payload;
            }

       // protected:
            std::string m_payload; ///< the content of the message
            emap(eref(m_payload))

}; // end of class Message
```

I checked and it seems this library only supports structs, which are mainly used in C, while it does not work with C++ classes.

**Comment by parnham** [comment]
We use it with both structs and classes - although with classes you must ensure that the mapping (emap) is declared in the public section. 
The issue you're seeing might be due to the lack of a default constructor in your class (you get the same problem with the ```std``` containers). 
So simply adding an additional 
``` 
    Message() {}
```
should help, I will update the assertion to include more information.

**Comment by grcasanova** [comment]
Okay thanks, now encoding seems to work.
I am a bit confused by the decoding part, how can you manage to assign directly the decoded object to a new class instance without overloading the _=_ operator?

For example
```
Message original_msg("...");
const std::string message = ent::encode<ent::json>(original_msg);
Message msg = ent::decode<ent::json>(message);
```
fails saying there's no suitable operator

**Comment by parnham** [comment]
Ah yes, there have been some very recent changes to the API and I need to correct the example in the readme. You can actually do either of
```cpp
auto msg = ent::decode<ent::json, Message>(data);
```
or
```cpp
Message msg;
ent::decode<ent::json>(data, msg);
```
